name: Auto Update Dependencies

on:
  schedule:
    - cron: '0 0 */14 * *'
  workflow_dispatch:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write

jobs:
  noop-job:
    runs-on: ubuntu-latest
    if: github.repository != 'chi0307/magnet'
    steps:
      - run: echo "Skipping workflow."

  update-dependencies:
    runs-on: ubuntu-latest
    if: github.repository == 'chi0307/magnet'
    steps:
      - name: Check out master branch
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Upgrade npm packages
        run: |
          pnpm install -g npm-check-updates
          ncu --doctor -u --doctorInstall "pnpm install" --doctorTest "pnpm run check" --peer

      - name: Set branch name
        id: set_branch_name
        run: |
          BRANCH_NAME=upgrade/packages-$(date +'%Y%m%d')
          echo "::set-output name=branch::$BRANCH_NAME"

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: ${{ steps.set_branch_name.outputs.branch }}
          base: master
          title: 'upgrade: auto update of dependencies'
          body: 'This PR updates the dependencies to their latest versions.'
          token: ${{ secrets.MACHINE_USER_PAT }}
          assignees: ${{ github.actor }}
          commit-message: 'upgrade: github auto upgrade all packages to latest'
          delete-branch: true
